<?php
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<fieldset>

<?php foreach ($this->form as $element) : ?>
   <?php if (!(($element instanceof Zend\Form\Element\Submit)) && (!($element instanceof Zend\Form\Element\Csrf))) : ?>
    <div class='control-group'>
        <label class='control_label' for="<?php echo $element->getName(); ?>"><?php echo $this->translate($element->getLabel()); ?></label>
        <div class="controls">
            <?php echo $this->formElement($element); ?>
            <?php echo $this->formElementErrors($element); ?>
        </div>
    </div>
   <?php else : ?>
    <br />
    <?php $element->setAttribute('class', 'btn btn-primary'); ?>
    <div class="form-actions">
        <?php echo $this->formElement($element); ?>
    </div>
   <?php endif; ?>
<?php endforeach; ?>

</fieldset>

<?php echo $this->form()->closeTag(); ?>